config/routes.rb
Rails.application.routes.draw do
  resources :sectors
  resources :technologies
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/welcome/:id', to: 'home#welcome'
  get '/personalize/:id', to: 'home#personalize'
  patch  'edit_user_investor_status/:id', to: 'home#edit_user_investor_status', as: :edit_user_investor_status
  patch  'edit_user_personalization/:id', to: 'home#edit_user_personalization', as: :edit_user_personalization

  root to: "home#main"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sector.rb
class Sector < ApplicationRecord
end

app/models/technology.rb
class Technology < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def main
  end

  def welcome
    @user = User.find(params["id"])
  end

  def edit_user_investor_status
    @user = User.find(params["id"])    
    @user.accredited_investor = params["user"]["accredited_investor"] == "1"
    case params["user"]["investing_as"]
    when "0"
      @user.investing_as = "individual"
    when "1"
      @user.investing_as = "non-institutional-entity"
    when "2"
      @user.investing_as = "institution"
    else
    end
    @user.save

    redirect_to :action => 'personalize'
  end

  def personalize
    @user = User.find(params["id"])
    @technologies = Technology.all
    @sectors = Sector.all
  end

  def edit_user_personalization
    @user = User.find(params["id"])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource)
    "/welcome/#{resource.id}"
  end
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :set_sector, only: [:show, :edit, :update, :destroy]

  # GET /sectors
  # GET /sectors.json
  def index
    @sectors = Sector.all
  end

  # GET /sectors/1
  # GET /sectors/1.json
  def show
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors
  # POST /sectors.json
  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to @sector, notice: 'Sector was successfully created.' }
        format.json { render :show, status: :created, location: @sector }
      else
        format.html { render :new }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sectors/1
  # PATCH/PUT /sectors/1.json
  def update
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to @sector, notice: 'Sector was successfully updated.' }
        format.json { render :show, status: :ok, location: @sector }
      else
        format.html { render :edit }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1
  # DELETE /sectors/1.json
  def destroy
    @sector.destroy
    respond_to do |format|
      format.html { redirect_to sectors_url, notice: 'Sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sector_params
      params.require(:sector).permit(:name)
    end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :set_technology, only: [:show, :edit, :update, :destroy]

  # GET /technologies
  # GET /technologies.json
  def index
    @technologies = Technology.all
  end

  # GET /technologies/1
  # GET /technologies/1.json
  def show
  end

  # GET /technologies/new
  def new
    @technology = Technology.new
  end

  # GET /technologies/1/edit
  def edit
  end

  # POST /technologies
  # POST /technologies.json
  def create
    @technology = Technology.new(technology_params)

    respond_to do |format|
      if @technology.save
        format.html { redirect_to @technology, notice: 'Technology was successfully created.' }
        format.json { render :show, status: :created, location: @technology }
      else
        format.html { render :new }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technologies/1
  # PATCH/PUT /technologies/1.json
  def update
    respond_to do |format|
      if @technology.update(technology_params)
        format.html { redirect_to @technology, notice: 'Technology was successfully updated.' }
        format.json { render :show, status: :ok, location: @technology }
      else
        format.html { render :edit }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.json
  def destroy
    @technology.destroy
    respond_to do |format|
      format.html { redirect_to technologies_url, notice: 'Technology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technology
      @technology = Technology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technology_params
      params.require(:technology).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/home/main.html.erb
Welcome to the main page of the demo.

<br>

<%= link_to("Sign up", new_user_registration_path) %>

<br>

<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

app/views/home/personalize.html.erb
<h3 class="center">We have a few questions to personalize your experience.</h3>

<h4 class="center">What technologies are you interested in?</h4>

<%= form_for(@user, url: edit_user_personalization_path(@user.id)) do |f| %>
  <div class="field center">
    <% @technologies.each do |tech| %>
      <%= f.check_box :accredited_investor%> 
      <%= f.label "#{tech.name}" %>
      <br>
    <% end %>
  </div>

  <h4 class="center">What sectors are you interested in?</h4>

  <div class="field center">
    <% @sectors.each do |sector| %>
      <%= f.check_box :accredited_investor%> 
      <%= f.label "#{sector.name}" %>
      <br>
    <% end %>
  </div>

  <h4 class="center">How many angel investments have you made?</h4>

  <div class="center">
    <%= react_component("HelloSlider", { count: 5 }) %>
  </div>

  <div class="actions center">
    <%= f.submit "Continue" %>
  </div>
<% end %>

app/views/home/welcome.html.erb
<h2 class="center">Welcome to Propel(x)</h2>

<p class="center">Thank you for signing up. You account is currently pending approval for full access to all of our investment opportunities. By law, we are required to ask you a few questions. To expedite your access to deals, please answer a short survery.</p>

<h3 class="center">I am investing as:</h3>

<%= form_for(@user, url: edit_user_investor_status_path(@user.id)) do |f| %>

  <ul class="field center">
    <li>
      <%= f.radio_button :investing_as, 0, checked: true %>
      <label>an individual</label>
    </li>

    <li>
      <%= f.radio_button :investing_as, 1, checked: false %> 
      <label>a non-institutional entity
      (e.g. trusts & personal LLCs)</label>
    </li>
    
    <li>
      <%= f.radio_button :investing_as, 2, checked: false %> 
      <label>an institution
      (e.g. VCs, corporate funds, family offices)</label>
    </li>
  </ul>

  <div class="field center">
    <%= f.check_box :accredited_investor%> I am an accredited investor
    <p>By joining, you are agreeing to Propel(x)'s Terms of Use and Privacy Policy</p>
  </div>

  <div class="actions center">
    <%= f.submit "Investment Objectives Survey" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoAppJan2018</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>

app/views/sectors/_form.html.erb
<%= form_with(model: sector, local: true) do |form| %>
  <% if sector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sector.errors.count, "error") %> prohibited this sector from being saved:</h2>

      <ul>
      <% sector.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :sector_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sectors/edit.html.erb
<h1>Editing Sector</h1>

<%= render 'form', sector: @sector %>

<%= link_to 'Show', @sector %> |
<%= link_to 'Back', sectors_path %>

app/views/sectors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sectors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sectors.each do |sector| %>
      <tr>
        <td><%= sector.name %></td>
        <td><%= link_to 'Show', sector %></td>
        <td><%= link_to 'Edit', edit_sector_path(sector) %></td>
        <td><%= link_to 'Destroy', sector, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sector', new_sector_path %>

app/views/sectors/new.html.erb
<h1>New Sector</h1>

<%= render 'form', sector: @sector %>

<%= link_to 'Back', sectors_path %>

app/views/sectors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sector.name %>
</p>

<%= link_to 'Edit', edit_sector_path(@sector) %> |
<%= link_to 'Back', sectors_path %>

app/views/technologies/_form.html.erb
<%= form_with(model: technology, local: true) do |form| %>
  <% if technology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(technology.errors.count, "error") %> prohibited this technology from being saved:</h2>

      <ul>
      <% technology.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :technology_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/technologies/edit.html.erb
<h1>Editing Technology</h1>

<%= render 'form', technology: @technology %>

<%= link_to 'Show', @technology %> |
<%= link_to 'Back', technologies_path %>

app/views/technologies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Technologies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @technologies.each do |technology| %>
      <tr>
        <td><%= technology.name %></td>
        <td><%= link_to 'Show', technology %></td>
        <td><%= link_to 'Edit', edit_technology_path(technology) %></td>
        <td><%= link_to 'Destroy', technology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Technology', new_technology_path %>

app/views/technologies/new.html.erb
<h1>New Technology</h1>

<%= render 'form', technology: @technology %>

<%= link_to 'Back', technologies_path %>

app/views/technologies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @technology.name %>
</p>

<%= link_to 'Edit', edit_technology_path(@technology) %> |
<%= link_to 'Back', technologies_path %>